version: 2.1
jobs:
  build:
    working_directory: ~/blog-api-auth
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test:cover
      - run:
          name: report
          command: npm run test:report
      - store_artifacts:
          path: test-report.json
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
